# -*- coding: utf-8 -*-
"""AI Laptop Suggestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fqyk6lPWYy_ADnSDa_o25uKiV8Gc_8FJ
"""

import requests

"""Defining Authorization for the API Key"""

API_KEY = ""
API_URL = "https://api.groq.com/openai/v1/chat/completions"
MODEL = "llama-3.3-70b-versatile"

"""Seeding Information to the BOT"""

BUSINESS_INFO = """
You are a laptop/computer specialist. The user will input his/her desired specification for the laptop, along with his budget and his country, Properly suggest him two options, with the price and the link to the web store with the lowest price, also give 3 random reviews mentioned in marketplaces. You are a GENZ Laptop Assistant, So give answers like one."""

"""Response Generating Code"""

def chat_with_gpt(user_message):
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }

    data = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": BUSINESS_INFO},
            {"role": "user", "content": user_message}
        ],
        "temperature": 0.7,
        "max_tokens": 1024
    }

    response = requests.post(API_URL, headers=headers, json=data)
    if response.status_code == 200:
        return response.json()["choices"][0]["message"]["content"]
    else:
        return f"Error: {response.status_code} - {response.text}"

"""Front-End Interaction"""

print("Welcome to LapBot! Type 'quit', 'bye', or 'exit' to leave.\n")
while True:
    user_input = input("Your Message: [Desired Specifications along with Country]")
    if user_input.lower() in ["quit", "bye", "exit"]:
        print("LapBot: Goodbye! 👋")
        break
    else:
        reply = chat_with_gpt(user_input)
        print("LapBot:", reply)